apiVersion: apps/v1
kind: Deployment
metadata:
  name: antibug-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antibug-account
      version: v1
  template:
    metadata:
      labels:
        app: antibug-account
        version: v1
    spec:
      containers:
      - name: antibug-account
        image: gidyon/antibug-account:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/antibug/accounts/health/ready
            port: 80
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 10
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/antibug/accounts/health/live
            port: 80
          initialDelaySeconds: 10
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 10
        env:
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-signing-key
              key: signing-key
        volumeMounts:
        - name: config
          mountPath: /app/configs/
          readOnly: true
        - name: mysql-creds
          mountPath: /app/secrets/mysql/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: account-istio-v1
      - name: mysql-creds
        secret:
          secretName: mysql-creds

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: antibug-account-hpa
  labels:
    app: antibug-account
spec:
  scaleTargetRef:
    kind: Deployment
    name: antibug-account
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
    service: account
spec:
  selector:
    app: antibug-account
  ports:
  - port: 80
    name: http
    protocol: TCP