// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Account represents user
type Account struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string   `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	ProfileUrl           string   `protobuf:"bytes,5,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	Gender               string   `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Group                string   `protobuf:"bytes,7,opt,name=group,proto3" json:"group,omitempty"`
	DeviceToken          string   `protobuf:"bytes,8,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Active               bool     `protobuf:"varint,9,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Account) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Account) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

func (m *Account) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Account) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *Account) GetDeviceToken() string {
	if m != nil {
		return m.DeviceToken
	}
	return ""
}

func (m *Account) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

// Job is an occupation
type Job struct {
	FacilityName         string   `protobuf:"bytes,1,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	FacilityId           string   `protobuf:"bytes,2,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	JobId                string   `protobuf:"bytes,4,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{1}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetFacilityName() string {
	if m != nil {
		return m.FacilityName
	}
	return ""
}

func (m *Job) GetFacilityId() string {
	if m != nil {
		return m.FacilityId
	}
	return ""
}

func (m *Job) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *Job) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// Jobs is collection of Jobs
type Jobs struct {
	Jobs                 []*Job   `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Jobs) Reset()         { *m = Jobs{} }
func (m *Jobs) String() string { return proto.CompactTextString(m) }
func (*Jobs) ProtoMessage()    {}
func (*Jobs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{2}
}

func (m *Jobs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Jobs.Unmarshal(m, b)
}
func (m *Jobs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Jobs.Marshal(b, m, deterministic)
}
func (m *Jobs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Jobs.Merge(m, src)
}
func (m *Jobs) XXX_Size() int {
	return xxx_messageInfo_Jobs.Size(m)
}
func (m *Jobs) XXX_DiscardUnknown() {
	xxx_messageInfo_Jobs.DiscardUnknown(m)
}

var xxx_messageInfo_Jobs proto.InternalMessageInfo

func (m *Jobs) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// Facility is a facility
type Facility struct {
	FacilityName         string   `protobuf:"bytes,1,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	FacilityId           string   `protobuf:"bytes,2,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Facility) Reset()         { *m = Facility{} }
func (m *Facility) String() string { return proto.CompactTextString(m) }
func (*Facility) ProtoMessage()    {}
func (*Facility) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{3}
}

func (m *Facility) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facility.Unmarshal(m, b)
}
func (m *Facility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facility.Marshal(b, m, deterministic)
}
func (m *Facility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facility.Merge(m, src)
}
func (m *Facility) XXX_Size() int {
	return xxx_messageInfo_Facility.Size(m)
}
func (m *Facility) XXX_DiscardUnknown() {
	xxx_messageInfo_Facility.DiscardUnknown(m)
}

var xxx_messageInfo_Facility proto.InternalMessageInfo

func (m *Facility) GetFacilityName() string {
	if m != nil {
		return m.FacilityName
	}
	return ""
}

func (m *Facility) GetFacilityId() string {
	if m != nil {
		return m.FacilityId
	}
	return ""
}

// StarredFacilities is health facilities where the user works or collaborates with or has starred
type StarredFacilities struct {
	Facilities           []*Facility `protobuf:"bytes,1,rep,name=facilities,proto3" json:"facilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StarredFacilities) Reset()         { *m = StarredFacilities{} }
func (m *StarredFacilities) String() string { return proto.CompactTextString(m) }
func (*StarredFacilities) ProtoMessage()    {}
func (*StarredFacilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{4}
}

func (m *StarredFacilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StarredFacilities.Unmarshal(m, b)
}
func (m *StarredFacilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StarredFacilities.Marshal(b, m, deterministic)
}
func (m *StarredFacilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StarredFacilities.Merge(m, src)
}
func (m *StarredFacilities) XXX_Size() int {
	return xxx_messageInfo_StarredFacilities.Size(m)
}
func (m *StarredFacilities) XXX_DiscardUnknown() {
	xxx_messageInfo_StarredFacilities.DiscardUnknown(m)
}

var xxx_messageInfo_StarredFacilities proto.InternalMessageInfo

func (m *StarredFacilities) GetFacilities() []*Facility {
	if m != nil {
		return m.Facilities
	}
	return nil
}

// Settings is user account settings
type Settings struct {
	Settings             map[string]bool `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Settings) Reset()         { *m = Settings{} }
func (m *Settings) String() string { return proto.CompactTextString(m) }
func (*Settings) ProtoMessage()    {}
func (*Settings) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{5}
}

func (m *Settings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Settings.Unmarshal(m, b)
}
func (m *Settings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Settings.Marshal(b, m, deterministic)
}
func (m *Settings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Settings.Merge(m, src)
}
func (m *Settings) XXX_Size() int {
	return xxx_messageInfo_Settings.Size(m)
}
func (m *Settings) XXX_DiscardUnknown() {
	xxx_messageInfo_Settings.DiscardUnknown(m)
}

var xxx_messageInfo_Settings proto.InternalMessageInfo

func (m *Settings) GetSettings() map[string]bool {
	if m != nil {
		return m.Settings
	}
	return nil
}

// LoginRequest is request to login
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{6}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

// LoginResponse is response after login
type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AccountId            string   `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountState         bool     `protobuf:"varint,3,opt,name=account_state,json=accountState,proto3" json:"account_state,omitempty"`
	AccountGroup         string   `protobuf:"bytes,5,opt,name=account_group,json=accountGroup,proto3" json:"account_group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{7}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *LoginResponse) GetAccountState() bool {
	if m != nil {
		return m.AccountState
	}
	return false
}

func (m *LoginResponse) GetAccountGroup() string {
	if m != nil {
		return m.AccountGroup
	}
	return ""
}

// CreateAccountRequest is request tp create an account
type CreateAccountRequest struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ConfirmPassword      string   `protobuf:"bytes,3,opt,name=confirm_password,json=confirmPassword,proto3" json:"confirm_password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{8}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *CreateAccountRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateAccountRequest) GetConfirmPassword() string {
	if m != nil {
		return m.ConfirmPassword
	}
	return ""
}

// CreateAccountResponse contains account id
type CreateAccountResponse struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{9}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// ActivateAccountRequest is request to activate the account
type ActivateAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ByAdmin              bool     `protobuf:"varint,2,opt,name=by_admin,json=byAdmin,proto3" json:"by_admin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActivateAccountRequest) Reset()         { *m = ActivateAccountRequest{} }
func (m *ActivateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*ActivateAccountRequest) ProtoMessage()    {}
func (*ActivateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{10}
}

func (m *ActivateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActivateAccountRequest.Unmarshal(m, b)
}
func (m *ActivateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActivateAccountRequest.Marshal(b, m, deterministic)
}
func (m *ActivateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActivateAccountRequest.Merge(m, src)
}
func (m *ActivateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_ActivateAccountRequest.Size(m)
}
func (m *ActivateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActivateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActivateAccountRequest proto.InternalMessageInfo

func (m *ActivateAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *ActivateAccountRequest) GetByAdmin() bool {
	if m != nil {
		return m.ByAdmin
	}
	return false
}

// UpdateAccountRequest updates a user account
type UpdateAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{11}
}

func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (m *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(m, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateAccountRequest) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

// DeleteAccountRequest is request to delete account
type DeleteAccountRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{12}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// GetRequest is request to retrieve Jobs, Settings or StarredFacility
type GetRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{13}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

// UpdateSettingsRequest is request to update user settings
type UpdateSettingsRequest struct {
	AccountId            string    `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Settings             *Settings `protobuf:"bytes,2,opt,name=settings,proto3" json:"settings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UpdateSettingsRequest) Reset()         { *m = UpdateSettingsRequest{} }
func (m *UpdateSettingsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSettingsRequest) ProtoMessage()    {}
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{14}
}

func (m *UpdateSettingsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSettingsRequest.Unmarshal(m, b)
}
func (m *UpdateSettingsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSettingsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSettingsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSettingsRequest.Merge(m, src)
}
func (m *UpdateSettingsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSettingsRequest.Size(m)
}
func (m *UpdateSettingsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSettingsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSettingsRequest proto.InternalMessageInfo

func (m *UpdateSettingsRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateSettingsRequest) GetSettings() *Settings {
	if m != nil {
		return m.Settings
	}
	return nil
}

// UpdateJobsRequest is request to update users jobs
type UpdateJobsRequest struct {
	AccountId            string   `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Jobs                 []*Job   `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateJobsRequest) Reset()         { *m = UpdateJobsRequest{} }
func (m *UpdateJobsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateJobsRequest) ProtoMessage()    {}
func (*UpdateJobsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{15}
}

func (m *UpdateJobsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateJobsRequest.Unmarshal(m, b)
}
func (m *UpdateJobsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateJobsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateJobsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateJobsRequest.Merge(m, src)
}
func (m *UpdateJobsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateJobsRequest.Size(m)
}
func (m *UpdateJobsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateJobsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateJobsRequest proto.InternalMessageInfo

func (m *UpdateJobsRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateJobsRequest) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

// UpdateStarredFacilitiesRequest is request to update starred facility
type UpdateStarredFacilitiesRequest struct {
	AccountId            string      `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Facilities           []*Facility `protobuf:"bytes,2,rep,name=facilities,proto3" json:"facilities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UpdateStarredFacilitiesRequest) Reset()         { *m = UpdateStarredFacilitiesRequest{} }
func (m *UpdateStarredFacilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStarredFacilitiesRequest) ProtoMessage()    {}
func (*UpdateStarredFacilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{16}
}

func (m *UpdateStarredFacilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStarredFacilitiesRequest.Unmarshal(m, b)
}
func (m *UpdateStarredFacilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStarredFacilitiesRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStarredFacilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStarredFacilitiesRequest.Merge(m, src)
}
func (m *UpdateStarredFacilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStarredFacilitiesRequest.Size(m)
}
func (m *UpdateStarredFacilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStarredFacilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStarredFacilitiesRequest proto.InternalMessageInfo

func (m *UpdateStarredFacilitiesRequest) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *UpdateStarredFacilitiesRequest) GetFacilities() []*Facility {
	if m != nil {
		return m.Facilities
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "antibug.account.Account")
	proto.RegisterType((*Job)(nil), "antibug.account.Job")
	proto.RegisterType((*Jobs)(nil), "antibug.account.Jobs")
	proto.RegisterType((*Facility)(nil), "antibug.account.Facility")
	proto.RegisterType((*StarredFacilities)(nil), "antibug.account.StarredFacilities")
	proto.RegisterType((*Settings)(nil), "antibug.account.Settings")
	proto.RegisterMapType((map[string]bool)(nil), "antibug.account.Settings.SettingsEntry")
	proto.RegisterType((*LoginRequest)(nil), "antibug.account.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "antibug.account.LoginResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "antibug.account.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "antibug.account.CreateAccountResponse")
	proto.RegisterType((*ActivateAccountRequest)(nil), "antibug.account.ActivateAccountRequest")
	proto.RegisterType((*UpdateAccountRequest)(nil), "antibug.account.UpdateAccountRequest")
	proto.RegisterType((*DeleteAccountRequest)(nil), "antibug.account.DeleteAccountRequest")
	proto.RegisterType((*GetRequest)(nil), "antibug.account.GetRequest")
	proto.RegisterType((*UpdateSettingsRequest)(nil), "antibug.account.UpdateSettingsRequest")
	proto.RegisterType((*UpdateJobsRequest)(nil), "antibug.account.UpdateJobsRequest")
	proto.RegisterType((*UpdateStarredFacilitiesRequest)(nil), "antibug.account.UpdateStarredFacilitiesRequest")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 1307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4d, 0x6f, 0x13, 0xc7,
	0x1b, 0xd7, 0xda, 0x21, 0x71, 0x1e, 0x27, 0x7f, 0x60, 0xe4, 0xf0, 0x37, 0xa6, 0xc0, 0x32, 0x14,
	0x12, 0x0c, 0xf6, 0xa6, 0x26, 0xa0, 0x12, 0x2a, 0xb5, 0x21, 0x84, 0x28, 0x08, 0x21, 0xea, 0x94,
	0x4b, 0xd5, 0x2a, 0xda, 0x97, 0xc9, 0x66, 0xc2, 0x7a, 0x67, 0x3b, 0x33, 0x26, 0x98, 0x96, 0x4b,
	0xd5, 0x43, 0x0f, 0x55, 0xa5, 0xb6, 0xaa, 0x54, 0xf5, 0xda, 0x4f, 0xd0, 0x2f, 0xc0, 0xb9, 0xf7,
	0x7e, 0x85, 0x7e, 0x8b, 0x5e, 0xaa, 0x99, 0x9d, 0x75, 0x9c, 0x38, 0xeb, 0x38, 0x55, 0x4f, 0xd9,
	0xe7, 0x65, 0x9e, 0x97, 0xdf, 0x3c, 0xcf, 0x2f, 0x63, 0x98, 0x75, 0x7d, 0x9f, 0x75, 0x63, 0xd9,
	0x4c, 0x38, 0x93, 0x0c, 0x9d, 0x76, 0x63, 0x49, 0xbd, 0x6e, 0xd8, 0x34, 0xea, 0xda, 0x3b, 0x21,
	0x63, 0x61, 0x44, 0x1c, 0x37, 0xa1, 0x8e, 0x1b, 0xc7, 0x4c, 0xba, 0x92, 0xb2, 0x58, 0xa4, 0xee,
	0xb5, 0x0b, 0xc6, 0xaa, 0x25, 0xaf, 0xbb, 0xed, 0x90, 0x4e, 0x22, 0x7b, 0xc6, 0x78, 0x4b, 0xff,
	0xf1, 0x1b, 0x21, 0x89, 0x1b, 0x62, 0xcf, 0x0d, 0x43, 0xc2, 0x1d, 0x96, 0xe8, 0xe3, 0xc3, 0xa1,
	0xf0, 0xdf, 0x16, 0x4c, 0xad, 0xa4, 0x49, 0xd1, 0x45, 0x80, 0x6d, 0xca, 0x85, 0xdc, 0x8a, 0xdd,
	0x0e, 0xa9, 0x5a, 0xb6, 0xb5, 0x30, 0xdd, 0x9e, 0xd6, 0x9a, 0xa7, 0x6e, 0x87, 0xa0, 0x0b, 0x30,
	0x1d, 0xb9, 0x99, 0xb5, 0xa0, 0xad, 0x25, 0xa5, 0xd0, 0xc6, 0x0a, 0x9c, 0x22, 0x1d, 0x97, 0x46,
	0xd5, 0xa2, 0x36, 0xa4, 0x82, 0xd2, 0x26, 0x3b, 0x2c, 0x26, 0xd5, 0x89, 0x54, 0xab, 0x05, 0x74,
	0x19, 0xca, 0x09, 0x67, 0xdb, 0x34, 0x22, 0x5b, 0x5d, 0x1e, 0x55, 0x4f, 0x69, 0x1b, 0x18, 0xd5,
	0x73, 0x1e, 0xa1, 0x73, 0x30, 0x19, 0x92, 0x38, 0x20, 0xbc, 0x3a, 0xa9, 0x6d, 0x46, 0x52, 0xe1,
	0x42, 0xce, 0xba, 0x49, 0x75, 0x2a, 0x0d, 0xa7, 0x05, 0x74, 0x05, 0x66, 0x02, 0xf2, 0x92, 0xfa,
	0x64, 0x4b, 0xb2, 0x17, 0x24, 0xae, 0x96, 0xb4, 0xb1, 0x9c, 0xea, 0x3e, 0x51, 0x2a, 0x15, 0xd0,
	0xf5, 0x25, 0x7d, 0x49, 0xaa, 0xd3, 0xb6, 0xb5, 0x50, 0x6a, 0x1b, 0x09, 0xff, 0x62, 0x41, 0xf1,
	0x31, 0xf3, 0xd0, 0x55, 0x98, 0xdd, 0x76, 0x7d, 0x1a, 0x51, 0xd9, 0x1b, 0x6c, 0x7e, 0x26, 0x53,
	0xea, 0x16, 0x2f, 0x43, 0xb9, 0xef, 0x44, 0x03, 0x83, 0x00, 0x64, 0xaa, 0x8d, 0x00, 0x21, 0x98,
	0xe0, 0x2c, 0x22, 0x06, 0x02, 0xfd, 0x8d, 0xe6, 0x60, 0x72, 0x97, 0x79, 0xca, 0xdf, 0x40, 0xb0,
	0xcb, 0xbc, 0x8d, 0x00, 0xd9, 0x50, 0x0e, 0x88, 0xf0, 0x39, 0xd5, 0x17, 0x63, 0x20, 0x18, 0x54,
	0xe1, 0x45, 0x98, 0x78, 0xcc, 0x3c, 0x81, 0x16, 0x60, 0x62, 0x97, 0x79, 0xa2, 0x6a, 0xd9, 0xc5,
	0x85, 0x72, 0xab, 0xd2, 0x3c, 0x34, 0x29, 0xcd, 0xc7, 0xcc, 0x6b, 0x6b, 0x0f, 0xfc, 0x0c, 0x4a,
	0x8f, 0x4c, 0x31, 0xff, 0x4d, 0x43, 0xf8, 0x29, 0x9c, 0xdd, 0x94, 0x2e, 0xe7, 0x24, 0x30, 0x81,
	0x29, 0x11, 0xe8, 0x1e, 0x64, 0x2e, 0x94, 0x64, 0x65, 0x9d, 0x1f, 0x2a, 0x2b, 0xab, 0xa4, 0x3d,
	0xe0, 0x8c, 0xbf, 0xb3, 0xa0, 0xb4, 0x49, 0xa4, 0xa4, 0x71, 0x28, 0xd0, 0x2a, 0x94, 0x84, 0xf9,
	0x36, 0x51, 0xe6, 0x87, 0xa2, 0x64, 0xce, 0xfd, 0x8f, 0xb5, 0x58, 0xf2, 0x5e, 0xbb, 0x7f, 0xb0,
	0x76, 0x1f, 0x66, 0x0f, 0x98, 0xd0, 0x19, 0x28, 0xbe, 0x20, 0x3d, 0xd3, 0xae, 0xfa, 0x54, 0x43,
	0xf3, 0xd2, 0x8d, 0xba, 0xe9, 0xc8, 0x96, 0xda, 0xa9, 0xb0, 0x5c, 0x78, 0xdf, 0xc2, 0x8f, 0x60,
	0xe6, 0x09, 0x0b, 0x69, 0xdc, 0x26, 0x5f, 0x74, 0x89, 0x90, 0xa8, 0x06, 0xa5, 0xae, 0x20, 0x7c,
	0x00, 0xaf, 0xbe, 0xac, 0x6c, 0x89, 0x2b, 0xc4, 0x1e, 0xe3, 0x19, 0x50, 0x7d, 0x19, 0x7f, 0x6f,
	0xc1, 0xac, 0x09, 0x24, 0x12, 0x16, 0x0b, 0xbd, 0x0d, 0xe9, 0x2c, 0xa6, 0x61, 0x52, 0x41, 0xed,
	0x97, 0x69, 0x6c, 0x1f, 0xee, 0x69, 0xa3, 0xd9, 0x08, 0xd4, 0x9d, 0x65, 0x66, 0x21, 0x5d, 0x99,
	0xce, 0x51, 0xa9, 0x3d, 0x63, 0x94, 0x9b, 0x4a, 0x37, 0xe8, 0x94, 0xae, 0x42, 0x3a, 0x3a, 0x99,
	0xd3, 0xba, 0xd2, 0xe1, 0x1f, 0x2c, 0xa8, 0xac, 0x72, 0xe2, 0x4a, 0x62, 0x56, 0x3b, 0xeb, 0xb0,
	0x05, 0x53, 0xc6, 0x51, 0x57, 0x56, 0x6e, 0x55, 0x87, 0x20, 0xcf, 0x4e, 0x64, 0x8e, 0xa3, 0x3a,
	0x47, 0x37, 0xe0, 0x8c, 0xcf, 0xe2, 0x6d, 0xca, 0x3b, 0x5b, 0x7d, 0x9f, 0x74, 0xfa, 0x4f, 0x1b,
	0xfd, 0xb3, 0x0c, 0xa4, 0xbb, 0x30, 0x77, 0xa8, 0x24, 0x83, 0xd5, 0x41, 0x54, 0xac, 0x43, 0xa8,
	0xe0, 0x36, 0x9c, 0x5b, 0x51, 0xcb, 0x3a, 0xdc, 0xcc, 0xe8, 0x83, 0xe8, 0x3c, 0x94, 0xbc, 0xde,
	0x96, 0x1b, 0x74, 0x68, 0x6c, 0xae, 0x7e, 0xca, 0xeb, 0xad, 0x28, 0x11, 0x53, 0xa8, 0x3c, 0x4f,
	0x82, 0x13, 0x47, 0x1c, 0x40, 0xaf, 0x30, 0x26, 0x7a, 0xf8, 0x0e, 0x54, 0x1e, 0x92, 0x88, 0x9c,
	0x30, 0x15, 0xbe, 0x09, 0xb0, 0x4e, 0xc6, 0x75, 0xee, 0xc0, 0x5c, 0xda, 0x4e, 0xb6, 0x0a, 0x63,
	0xf6, 0x73, 0x67, 0x60, 0x03, 0xd3, 0x86, 0xce, 0xe7, 0x6e, 0xe0, 0xfe, 0xce, 0xe1, 0xcf, 0xe0,
	0x6c, 0x9a, 0x4e, 0xf1, 0xd3, 0x98, 0xa9, 0x32, 0x16, 0x2b, 0x1c, 0xcb, 0x62, 0xaf, 0xe1, 0x92,
	0x69, 0xe6, 0x30, 0xf3, 0x8c, 0x99, 0xea, 0x20, 0x3f, 0x15, 0x4e, 0xc0, 0x4f, 0xad, 0xb7, 0x65,
	0x00, 0x73, 0x4f, 0x2b, 0xcf, 0x36, 0x50, 0x17, 0x4e, 0xe9, 0xb5, 0x46, 0x17, 0x87, 0x8e, 0x0f,
	0xf2, 0x46, 0xed, 0x52, 0x9e, 0x39, 0x9d, 0x70, 0xdc, 0xf8, 0xfa, 0xcf, 0xbf, 0x7e, 0x2a, 0xcc,
	0x63, 0x6c, 0xfe, 0x9d, 0x6b, 0x5f, 0xc7, 0xf8, 0x0a, 0x47, 0xfd, 0x2f, 0x62, 0xb1, 0x13, 0xa9,
	0x33, 0xcb, 0x56, 0x1d, 0x29, 0x3a, 0x39, 0xb0, 0x2a, 0xe8, 0xda, 0x50, 0x82, 0xa3, 0xb6, 0xbb,
	0x76, 0xfd, 0x38, 0x37, 0x53, 0x4f, 0x53, 0xd7, 0xb3, 0x80, 0xaf, 0x8e, 0xac, 0xc7, 0xd7, 0x67,
	0x55, 0x41, 0xdf, 0x58, 0x70, 0xfa, 0xd0, 0x0e, 0xa2, 0xf9, 0x23, 0x46, 0xff, 0xa8, 0x2d, 0xad,
	0x9d, 0x6b, 0xa6, 0x8f, 0x95, 0x66, 0xf6, 0x58, 0x69, 0xae, 0xa9, 0xc7, 0x0a, 0x5e, 0xd4, 0x45,
	0xd4, 0xf1, 0xb5, 0x91, 0x45, 0xb8, 0x26, 0xa8, 0x2a, 0xe3, 0x0d, 0xcc, 0x1e, 0xd8, 0xda, 0x23,
	0x60, 0x39, 0x6a, 0xab, 0x73, 0x2b, 0x30, 0xd7, 0xd2, 0xca, 0xb9, 0x96, 0x2f, 0xf7, 0x87, 0xec,
	0x8d, 0x4a, 0xcf, 0xf4, 0x4a, 0x66, 0xb9, 0x2f, 0x0c, 0xe5, 0xde, 0xdf, 0xd7, 0x5a, 0x2e, 0x2f,
	0xe0, 0xba, 0xce, 0xf9, 0x2e, 0x1a, 0x23, 0x27, 0x7a, 0x0d, 0xe5, 0x75, 0x22, 0xfb, 0xff, 0x2f,
	0x47, 0x66, 0xcc, 0x5f, 0x5c, 0x7c, 0x5b, 0xa7, 0x6c, 0xa0, 0x9b, 0xc7, 0xa7, 0x74, 0xb2, 0x1d,
	0x47, 0xdf, 0x5a, 0xf0, 0xbf, 0x83, 0x9c, 0x82, 0xae, 0xe7, 0xa0, 0x7d, 0x88, 0x74, 0x72, 0xe1,
	0xbe, 0xab, 0xeb, 0x58, 0xac, 0x9d, 0xa4, 0x0e, 0x85, 0x7b, 0x0c, 0x53, 0xeb, 0x44, 0xea, 0xb7,
	0xd0, 0x48, 0x08, 0xe6, 0x8e, 0x22, 0x15, 0x81, 0x1d, 0x9d, 0xf6, 0x06, 0x9a, 0x1f, 0x23, 0xad,
	0x22, 0x20, 0xf4, 0x15, 0xc0, 0x3e, 0xbd, 0x21, 0x9c, 0xd3, 0xf5, 0x00, 0xf7, 0xe5, 0x76, 0xdc,
	0xd2, 0xa9, 0x6f, 0xd5, 0xc6, 0x4d, 0xad, 0xba, 0xfd, 0xd9, 0x82, 0x8a, 0xba, 0xf5, 0xa1, 0x67,
	0xd7, 0xc8, 0xde, 0x87, 0xab, 0x1c, 0x0a, 0x80, 0x3f, 0xd0, 0xd5, 0xdc, 0x45, 0x4b, 0xe3, 0xe0,
	0x2f, 0x5d, 0x4e, 0x82, 0xc6, 0x3e, 0x35, 0xa2, 0xdf, 0x2c, 0xf8, 0x7f, 0x0e, 0x2f, 0x23, 0x27,
	0x6f, 0x32, 0x72, 0x18, 0x3c, 0x17, 0xb0, 0x0f, 0x75, 0x89, 0xf7, 0x6a, 0xff, 0xaa, 0xc4, 0x65,
	0xab, 0xfe, 0xe0, 0x6d, 0xe1, 0xc7, 0x95, 0xdf, 0x0b, 0xe8, 0x0f, 0x4d, 0x58, 0xda, 0xd7, 0xde,
	0x24, 0x5c, 0xfd, 0x0e, 0xc0, 0x9f, 0xc3, 0x15, 0xd7, 0xf7, 0x55, 0x1c, 0x5b, 0xa4, 0x2a, 0xbb,
	0x61, 0x9b, 0x14, 0x76, 0xc2, 0xd9, 0x2e, 0xf1, 0x25, 0xba, 0xb2, 0x23, 0x65, 0x22, 0x96, 0x1d,
	0x27, 0xa4, 0x72, 0xa7, 0xeb, 0x35, 0x7d, 0xd6, 0x71, 0x42, 0x1a, 0xf4, 0x14, 0x13, 0xa5, 0xae,
	0xb5, 0xb9, 0x90, 0x06, 0x84, 0xc5, 0x3b, 0xae, 0x4f, 0xf8, 0x47, 0xa1, 0xfa, 0x95, 0xa3, 0xbc,
	0xea, 0x1f, 0x43, 0xe5, 0xc1, 0xe6, 0x43, 0xfb, 0x76, 0x63, 0x35, 0x72, 0xbb, 0x82, 0xd8, 0x4f,
	0xa8, 0x4f, 0xd4, 0xeb, 0xe6, 0xde, 0xb1, 0x11, 0x1d, 0x2f, 0x62, 0x9e, 0xd3, 0x71, 0x85, 0x24,
	0xdc, 0x79, 0xb2, 0xb1, 0xba, 0xf6, 0x74, 0x73, 0xad, 0x29, 0x5f, 0xc9, 0x56, 0xf1, 0xbd, 0xe6,
	0x62, 0xbd, 0x68, 0x15, 0x26, 0x5a, 0x67, 0xdc, 0x24, 0x89, 0xa8, 0xaf, 0x7f, 0xb8, 0x39, 0xbb,
	0x82, 0xc5, 0xcb, 0x43, 0x9a, 0xf6, 0x7d, 0x28, 0x2e, 0x2d, 0x2e, 0xa1, 0x25, 0xa8, 0xb7, 0x89,
	0xec, 0xf2, 0x98, 0x04, 0xf6, 0xde, 0x0e, 0x89, 0x6d, 0xb9, 0x43, 0x6c, 0x4e, 0x04, 0xeb, 0x72,
	0x9f, 0xd8, 0x01, 0x23, 0xc2, 0x8e, 0x99, 0xb4, 0xc9, 0x2b, 0x2a, 0x64, 0x13, 0x4d, 0xc2, 0xc4,
	0xaf, 0x05, 0x6b, 0xf2, 0xd3, 0xec, 0xb9, 0xe2, 0x4d, 0xea, 0x1b, 0xb9, 0xfd, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x6a, 0x9d, 0x60, 0x60, 0xa0, 0x0e, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountAPIClient is the client API for AccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountAPIClient interface {
	// Logins a user
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Creates account for user
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// Activates a user account
	ActivateAccount(ctx context.Context, in *ActivateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Updates an account
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves an account
	GetAccount(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Account, error)
	// Retrieves a user settings
	GetSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Settings, error)
	// Updates a user settings
	UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves a user list of jobs
	GetJobs(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Jobs, error)
	// Updates a user list of job(s)
	UpdateJobs(ctx context.Context, in *UpdateJobsRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves a user list of stared facilities
	GetStarredFacilities(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*StarredFacilities, error)
	// Updates a user list of stared facilities
	UpdateStarredFacilities(ctx context.Context, in *UpdateStarredFacilitiesRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type accountAPIClient struct {
	cc *grpc.ClientConn
}

func NewAccountAPIClient(cc *grpc.ClientConn) AccountAPIClient {
	return &accountAPIClient{cc}
}

func (c *accountAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) ActivateAccount(ctx context.Context, in *ActivateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/ActivateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetAccount(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Settings, error) {
	out := new(Settings)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/GetSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) UpdateSettings(ctx context.Context, in *UpdateSettingsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/UpdateSettings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetJobs(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Jobs, error) {
	out := new(Jobs)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/GetJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) UpdateJobs(ctx context.Context, in *UpdateJobsRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/UpdateJobs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) GetStarredFacilities(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*StarredFacilities, error) {
	out := new(StarredFacilities)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/GetStarredFacilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountAPIClient) UpdateStarredFacilities(ctx context.Context, in *UpdateStarredFacilitiesRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/antibug.account.AccountAPI/UpdateStarredFacilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAPIServer is the server API for AccountAPI service.
type AccountAPIServer interface {
	// Logins a user
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Creates account for user
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// Activates a user account
	ActivateAccount(context.Context, *ActivateAccountRequest) (*empty.Empty, error)
	// Updates an account
	UpdateAccount(context.Context, *UpdateAccountRequest) (*empty.Empty, error)
	// Retrieves an account
	GetAccount(context.Context, *GetRequest) (*Account, error)
	// Retrieves a user settings
	GetSettings(context.Context, *GetRequest) (*Settings, error)
	// Updates a user settings
	UpdateSettings(context.Context, *UpdateSettingsRequest) (*empty.Empty, error)
	// Retrieves a user list of jobs
	GetJobs(context.Context, *GetRequest) (*Jobs, error)
	// Updates a user list of job(s)
	UpdateJobs(context.Context, *UpdateJobsRequest) (*empty.Empty, error)
	// Retrieves a user list of stared facilities
	GetStarredFacilities(context.Context, *GetRequest) (*StarredFacilities, error)
	// Updates a user list of stared facilities
	UpdateStarredFacilities(context.Context, *UpdateStarredFacilitiesRequest) (*empty.Empty, error)
}

func RegisterAccountAPIServer(s *grpc.Server, srv AccountAPIServer) {
	s.RegisterService(&_AccountAPI_serviceDesc, srv)
}

func _AccountAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_ActivateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).ActivateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/ActivateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).ActivateAccount(ctx, req.(*ActivateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetAccount(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/GetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetSettings(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_UpdateSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).UpdateSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/UpdateSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).UpdateSettings(ctx, req.(*UpdateSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/GetJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetJobs(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_UpdateJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).UpdateJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/UpdateJobs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).UpdateJobs(ctx, req.(*UpdateJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_GetStarredFacilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetStarredFacilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/GetStarredFacilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetStarredFacilities(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountAPI_UpdateStarredFacilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStarredFacilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).UpdateStarredFacilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.account.AccountAPI/UpdateStarredFacilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).UpdateStarredFacilities(ctx, req.(*UpdateStarredFacilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "antibug.account.AccountAPI",
	HandlerType: (*AccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AccountAPI_Login_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _AccountAPI_CreateAccount_Handler,
		},
		{
			MethodName: "ActivateAccount",
			Handler:    _AccountAPI_ActivateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AccountAPI_UpdateAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccountAPI_GetAccount_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _AccountAPI_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSettings",
			Handler:    _AccountAPI_UpdateSettings_Handler,
		},
		{
			MethodName: "GetJobs",
			Handler:    _AccountAPI_GetJobs_Handler,
		},
		{
			MethodName: "UpdateJobs",
			Handler:    _AccountAPI_UpdateJobs_Handler,
		},
		{
			MethodName: "GetStarredFacilities",
			Handler:    _AccountAPI_GetStarredFacilities_Handler,
		},
		{
			MethodName: "UpdateStarredFacilities",
			Handler:    _AccountAPI_UpdateStarredFacilities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}
