apiVersion: apps/v1
kind: Deployment
metadata:
  name: antibug-culture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: antibug-culture
  template:
    metadata:
      labels:
        app: antibug-culture
    spec:
      containers:
      - name: antibug-culture
        image: gidyon/antibug-culture:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        env:
        - name: JWT_SIGNING_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-signing-key
              key: signing-key
        readinessProbe: # Checks that the container is started
          httpGet:
            path: /api/antibug/cultures/health/ready
            port: 80
          initialDelaySeconds: 0
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 10
        livenessProbe: # Checks that the container is running
          httpGet:
            path: /api/antibug/cultures/health/live
            port: 80
          initialDelaySeconds: 10
          failureThreshold: 3
          successThreshold: 1
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /app/configs/
          readOnly: true
        - name: mysql-creds
          mountPath: /app/secrets/mysql/
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: culture-istio-v1
      - name: mysql-creds
        secret:
          secretName: mysql-creds

---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "antibug-culture-hpa"
  labels:
    app: "antibug-culture"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "antibug-culture"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name: culture
  labels:
    app: culture
spec:
  selector:
    app: antibug-culture
  ports:
  - port: 80
    name: http
    targetPort: http
    protocol: TCP