// Code generated by protoc-gen-go. DO NOT EDIT.
// source: facility.proto

package facility

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Facility is a place where like hospital or learning institution
type Facility struct {
	FacilityId           int64    `protobuf:"varint,1,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	FacilityName         string   `protobuf:"bytes,2,opt,name=facility_name,json=facilityName,proto3" json:"facility_name,omitempty"`
	County               string   `protobuf:"bytes,3,opt,name=county,proto3" json:"county,omitempty"`
	CountyCode           int32    `protobuf:"varint,4,opt,name=county_code,json=countyCode,proto3" json:"county_code,omitempty"`
	SubCounty            string   `protobuf:"bytes,5,opt,name=sub_county,json=subCounty,proto3" json:"sub_county,omitempty"`
	SubCountyCode        int32    `protobuf:"varint,6,opt,name=sub_county_code,json=subCountyCode,proto3" json:"sub_county_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Facility) Reset()         { *m = Facility{} }
func (m *Facility) String() string { return proto.CompactTextString(m) }
func (*Facility) ProtoMessage()    {}
func (*Facility) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{0}
}

func (m *Facility) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facility.Unmarshal(m, b)
}
func (m *Facility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facility.Marshal(b, m, deterministic)
}
func (m *Facility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facility.Merge(m, src)
}
func (m *Facility) XXX_Size() int {
	return xxx_messageInfo_Facility.Size(m)
}
func (m *Facility) XXX_DiscardUnknown() {
	xxx_messageInfo_Facility.DiscardUnknown(m)
}

var xxx_messageInfo_Facility proto.InternalMessageInfo

func (m *Facility) GetFacilityId() int64 {
	if m != nil {
		return m.FacilityId
	}
	return 0
}

func (m *Facility) GetFacilityName() string {
	if m != nil {
		return m.FacilityName
	}
	return ""
}

func (m *Facility) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *Facility) GetCountyCode() int32 {
	if m != nil {
		return m.CountyCode
	}
	return 0
}

func (m *Facility) GetSubCounty() string {
	if m != nil {
		return m.SubCounty
	}
	return ""
}

func (m *Facility) GetSubCountyCode() int32 {
	if m != nil {
		return m.SubCountyCode
	}
	return 0
}

// SubCounty is an area within a county
type SubCounty struct {
	SubCounty            string   `protobuf:"bytes,1,opt,name=sub_county,json=subCounty,proto3" json:"sub_county,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubCounty) Reset()         { *m = SubCounty{} }
func (m *SubCounty) String() string { return proto.CompactTextString(m) }
func (*SubCounty) ProtoMessage()    {}
func (*SubCounty) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{1}
}

func (m *SubCounty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubCounty.Unmarshal(m, b)
}
func (m *SubCounty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubCounty.Marshal(b, m, deterministic)
}
func (m *SubCounty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubCounty.Merge(m, src)
}
func (m *SubCounty) XXX_Size() int {
	return xxx_messageInfo_SubCounty.Size(m)
}
func (m *SubCounty) XXX_DiscardUnknown() {
	xxx_messageInfo_SubCounty.DiscardUnknown(m)
}

var xxx_messageInfo_SubCounty proto.InternalMessageInfo

func (m *SubCounty) GetSubCounty() string {
	if m != nil {
		return m.SubCounty
	}
	return ""
}

func (m *SubCounty) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// County or state
type County struct {
	County               string   `protobuf:"bytes,1,opt,name=county,proto3" json:"county,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *County) Reset()         { *m = County{} }
func (m *County) String() string { return proto.CompactTextString(m) }
func (*County) ProtoMessage()    {}
func (*County) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{2}
}

func (m *County) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_County.Unmarshal(m, b)
}
func (m *County) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_County.Marshal(b, m, deterministic)
}
func (m *County) XXX_Merge(src proto.Message) {
	xxx_messageInfo_County.Merge(m, src)
}
func (m *County) XXX_Size() int {
	return xxx_messageInfo_County.Size(m)
}
func (m *County) XXX_DiscardUnknown() {
	xxx_messageInfo_County.DiscardUnknown(m)
}

var xxx_messageInfo_County proto.InternalMessageInfo

func (m *County) GetCounty() string {
	if m != nil {
		return m.County
	}
	return ""
}

func (m *County) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

// AddFacilityRequest is request to add a facility resource to server
type AddFacilityRequest struct {
	Facility             *Facility `protobuf:"bytes,2,opt,name=facility,proto3" json:"facility,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AddFacilityRequest) Reset()         { *m = AddFacilityRequest{} }
func (m *AddFacilityRequest) String() string { return proto.CompactTextString(m) }
func (*AddFacilityRequest) ProtoMessage()    {}
func (*AddFacilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{3}
}

func (m *AddFacilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFacilityRequest.Unmarshal(m, b)
}
func (m *AddFacilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFacilityRequest.Marshal(b, m, deterministic)
}
func (m *AddFacilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFacilityRequest.Merge(m, src)
}
func (m *AddFacilityRequest) XXX_Size() int {
	return xxx_messageInfo_AddFacilityRequest.Size(m)
}
func (m *AddFacilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFacilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddFacilityRequest proto.InternalMessageInfo

func (m *AddFacilityRequest) GetFacility() *Facility {
	if m != nil {
		return m.Facility
	}
	return nil
}

// AddFacilityResponse is response to AddFacility call containing the id of the newly created facility resource
type AddFacilityResponse struct {
	FacilityId           string   `protobuf:"bytes,1,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddFacilityResponse) Reset()         { *m = AddFacilityResponse{} }
func (m *AddFacilityResponse) String() string { return proto.CompactTextString(m) }
func (*AddFacilityResponse) ProtoMessage()    {}
func (*AddFacilityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{4}
}

func (m *AddFacilityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddFacilityResponse.Unmarshal(m, b)
}
func (m *AddFacilityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddFacilityResponse.Marshal(b, m, deterministic)
}
func (m *AddFacilityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddFacilityResponse.Merge(m, src)
}
func (m *AddFacilityResponse) XXX_Size() int {
	return xxx_messageInfo_AddFacilityResponse.Size(m)
}
func (m *AddFacilityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddFacilityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddFacilityResponse proto.InternalMessageInfo

func (m *AddFacilityResponse) GetFacilityId() string {
	if m != nil {
		return m.FacilityId
	}
	return ""
}

// RemoveFacilityRequest is request to remove a facility resource from the server
type RemoveFacilityRequest struct {
	FacilityId           string   `protobuf:"bytes,2,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveFacilityRequest) Reset()         { *m = RemoveFacilityRequest{} }
func (m *RemoveFacilityRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveFacilityRequest) ProtoMessage()    {}
func (*RemoveFacilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{5}
}

func (m *RemoveFacilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveFacilityRequest.Unmarshal(m, b)
}
func (m *RemoveFacilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveFacilityRequest.Marshal(b, m, deterministic)
}
func (m *RemoveFacilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveFacilityRequest.Merge(m, src)
}
func (m *RemoveFacilityRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveFacilityRequest.Size(m)
}
func (m *RemoveFacilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveFacilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveFacilityRequest proto.InternalMessageInfo

func (m *RemoveFacilityRequest) GetFacilityId() string {
	if m != nil {
		return m.FacilityId
	}
	return ""
}

// GetFacilityRequest is request to retrieve a single facility resource
type GetFacilityRequest struct {
	FacilityId           string   `protobuf:"bytes,1,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetFacilityRequest) Reset()         { *m = GetFacilityRequest{} }
func (m *GetFacilityRequest) String() string { return proto.CompactTextString(m) }
func (*GetFacilityRequest) ProtoMessage()    {}
func (*GetFacilityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{6}
}

func (m *GetFacilityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetFacilityRequest.Unmarshal(m, b)
}
func (m *GetFacilityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetFacilityRequest.Marshal(b, m, deterministic)
}
func (m *GetFacilityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetFacilityRequest.Merge(m, src)
}
func (m *GetFacilityRequest) XXX_Size() int {
	return xxx_messageInfo_GetFacilityRequest.Size(m)
}
func (m *GetFacilityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetFacilityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetFacilityRequest proto.InternalMessageInfo

func (m *GetFacilityRequest) GetFacilityId() string {
	if m != nil {
		return m.FacilityId
	}
	return ""
}

// ListFacilitiesRequest is request to retrive a collection of facilitiese resource
type ListFacilitiesRequest struct {
	PageToken            int32    `protobuf:"varint,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListFacilitiesRequest) Reset()         { *m = ListFacilitiesRequest{} }
func (m *ListFacilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFacilitiesRequest) ProtoMessage()    {}
func (*ListFacilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{7}
}

func (m *ListFacilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListFacilitiesRequest.Unmarshal(m, b)
}
func (m *ListFacilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListFacilitiesRequest.Marshal(b, m, deterministic)
}
func (m *ListFacilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListFacilitiesRequest.Merge(m, src)
}
func (m *ListFacilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_ListFacilitiesRequest.Size(m)
}
func (m *ListFacilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListFacilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListFacilitiesRequest proto.InternalMessageInfo

func (m *ListFacilitiesRequest) GetPageToken() int32 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

func (m *ListFacilitiesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// SearchFacilitiesRequest is request to search for a facility
type SearchFacilitiesRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageToken            int32    `protobuf:"varint,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchFacilitiesRequest) Reset()         { *m = SearchFacilitiesRequest{} }
func (m *SearchFacilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*SearchFacilitiesRequest) ProtoMessage()    {}
func (*SearchFacilitiesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{8}
}

func (m *SearchFacilitiesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchFacilitiesRequest.Unmarshal(m, b)
}
func (m *SearchFacilitiesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchFacilitiesRequest.Marshal(b, m, deterministic)
}
func (m *SearchFacilitiesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchFacilitiesRequest.Merge(m, src)
}
func (m *SearchFacilitiesRequest) XXX_Size() int {
	return xxx_messageInfo_SearchFacilitiesRequest.Size(m)
}
func (m *SearchFacilitiesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchFacilitiesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchFacilitiesRequest proto.InternalMessageInfo

func (m *SearchFacilitiesRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *SearchFacilitiesRequest) GetPageToken() int32 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

func (m *SearchFacilitiesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// Facilities is a colection of facility resource
type Facilities struct {
	Facilities           []*Facility `protobuf:"bytes,1,rep,name=facilities,proto3" json:"facilities,omitempty"`
	NextPageToken        int32       `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Facilities) Reset()         { *m = Facilities{} }
func (m *Facilities) String() string { return proto.CompactTextString(m) }
func (*Facilities) ProtoMessage()    {}
func (*Facilities) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{9}
}

func (m *Facilities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Facilities.Unmarshal(m, b)
}
func (m *Facilities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Facilities.Marshal(b, m, deterministic)
}
func (m *Facilities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Facilities.Merge(m, src)
}
func (m *Facilities) XXX_Size() int {
	return xxx_messageInfo_Facilities.Size(m)
}
func (m *Facilities) XXX_DiscardUnknown() {
	xxx_messageInfo_Facilities.DiscardUnknown(m)
}

var xxx_messageInfo_Facilities proto.InternalMessageInfo

func (m *Facilities) GetFacilities() []*Facility {
	if m != nil {
		return m.Facilities
	}
	return nil
}

func (m *Facilities) GetNextPageToken() int32 {
	if m != nil {
		return m.NextPageToken
	}
	return 0
}

// Counties is a collection of county
type Counties struct {
	Counties             []*County `protobuf:"bytes,1,rep,name=counties,proto3" json:"counties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Counties) Reset()         { *m = Counties{} }
func (m *Counties) String() string { return proto.CompactTextString(m) }
func (*Counties) ProtoMessage()    {}
func (*Counties) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{10}
}

func (m *Counties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counties.Unmarshal(m, b)
}
func (m *Counties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counties.Marshal(b, m, deterministic)
}
func (m *Counties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counties.Merge(m, src)
}
func (m *Counties) XXX_Size() int {
	return xxx_messageInfo_Counties.Size(m)
}
func (m *Counties) XXX_DiscardUnknown() {
	xxx_messageInfo_Counties.DiscardUnknown(m)
}

var xxx_messageInfo_Counties proto.InternalMessageInfo

func (m *Counties) GetCounties() []*County {
	if m != nil {
		return m.Counties
	}
	return nil
}

// SubCounties is a collection of sub-counties resource
type SubCounties struct {
	SubCounties          []*SubCounty `protobuf:"bytes,1,rep,name=sub_counties,json=subCounties,proto3" json:"sub_counties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *SubCounties) Reset()         { *m = SubCounties{} }
func (m *SubCounties) String() string { return proto.CompactTextString(m) }
func (*SubCounties) ProtoMessage()    {}
func (*SubCounties) Descriptor() ([]byte, []int) {
	return fileDescriptor_e79ec3532db37ad6, []int{11}
}

func (m *SubCounties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubCounties.Unmarshal(m, b)
}
func (m *SubCounties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubCounties.Marshal(b, m, deterministic)
}
func (m *SubCounties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubCounties.Merge(m, src)
}
func (m *SubCounties) XXX_Size() int {
	return xxx_messageInfo_SubCounties.Size(m)
}
func (m *SubCounties) XXX_DiscardUnknown() {
	xxx_messageInfo_SubCounties.DiscardUnknown(m)
}

var xxx_messageInfo_SubCounties proto.InternalMessageInfo

func (m *SubCounties) GetSubCounties() []*SubCounty {
	if m != nil {
		return m.SubCounties
	}
	return nil
}

func init() {
	proto.RegisterType((*Facility)(nil), "antibug.facility.Facility")
	proto.RegisterType((*SubCounty)(nil), "antibug.facility.SubCounty")
	proto.RegisterType((*County)(nil), "antibug.facility.County")
	proto.RegisterType((*AddFacilityRequest)(nil), "antibug.facility.AddFacilityRequest")
	proto.RegisterType((*AddFacilityResponse)(nil), "antibug.facility.AddFacilityResponse")
	proto.RegisterType((*RemoveFacilityRequest)(nil), "antibug.facility.RemoveFacilityRequest")
	proto.RegisterType((*GetFacilityRequest)(nil), "antibug.facility.GetFacilityRequest")
	proto.RegisterType((*ListFacilitiesRequest)(nil), "antibug.facility.ListFacilitiesRequest")
	proto.RegisterType((*SearchFacilitiesRequest)(nil), "antibug.facility.SearchFacilitiesRequest")
	proto.RegisterType((*Facilities)(nil), "antibug.facility.Facilities")
	proto.RegisterType((*Counties)(nil), "antibug.facility.Counties")
	proto.RegisterType((*SubCounties)(nil), "antibug.facility.SubCounties")
}

func init() { proto.RegisterFile("facility.proto", fileDescriptor_e79ec3532db37ad6) }

var fileDescriptor_e79ec3532db37ad6 = []byte{
	// 945 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0xdd, 0x72, 0xdb, 0x44,
	0x14, 0x1e, 0xd9, 0x89, 0xb1, 0x8f, 0x9b, 0x34, 0xb3, 0x34, 0xc5, 0xe3, 0x34, 0x83, 0x50, 0x9b,
	0x26, 0x35, 0xb5, 0x54, 0x5c, 0xd3, 0x81, 0x30, 0xd3, 0x69, 0x1a, 0x02, 0x93, 0x99, 0xd0, 0x29,
	0x32, 0x57, 0xdc, 0x18, 0x59, 0x3a, 0x95, 0xb7, 0xb5, 0xb5, 0xaa, 0x76, 0xd5, 0x26, 0xe5, 0x67,
	0x98, 0x0e, 0x57, 0x5c, 0xc2, 0x1d, 0xc3, 0x6b, 0xf0, 0x04, 0xdc, 0x72, 0xc1, 0x0c, 0xaf, 0xc0,
	0x83, 0x30, 0x5a, 0x69, 0xe5, 0x1f, 0xd9, 0x35, 0x57, 0x96, 0xce, 0x9e, 0xef, 0xfb, 0xce, 0xee,
	0xf9, 0xce, 0xca, 0xb0, 0xf9, 0xc4, 0x71, 0xe9, 0x88, 0x8a, 0x0b, 0x33, 0x8c, 0x98, 0x60, 0x64,
	0xcb, 0x09, 0x04, 0x1d, 0xc4, 0xbe, 0xa9, 0xe2, 0xcd, 0x1d, 0x9f, 0x31, 0x7f, 0x84, 0x96, 0x5c,
	0x1f, 0xc4, 0x4f, 0x2c, 0x1c, 0x87, 0x2a, 0xbd, 0x79, 0x2d, 0x5b, 0x74, 0x42, 0x6a, 0x39, 0x41,
	0xc0, 0x84, 0x23, 0x28, 0x0b, 0x78, 0xb6, 0x7a, 0x5b, 0xfe, 0xb8, 0x6d, 0x1f, 0x83, 0x36, 0x7f,
	0xe9, 0xf8, 0x3e, 0x46, 0x16, 0x0b, 0x65, 0x46, 0x31, 0xdb, 0xf8, 0x5b, 0x83, 0xea, 0x67, 0x99,
	0x2a, 0x79, 0x17, 0xea, 0xaa, 0x82, 0x3e, 0xf5, 0x1a, 0x9a, 0xae, 0x1d, 0x94, 0x6d, 0x50, 0xa1,
	0x53, 0x8f, 0x5c, 0x87, 0x8d, 0x3c, 0x21, 0x70, 0xc6, 0xd8, 0x28, 0xe9, 0xda, 0x41, 0xcd, 0xbe,
	0xa4, 0x82, 0x8f, 0x9c, 0x31, 0x92, 0xab, 0x50, 0x71, 0x59, 0x1c, 0x88, 0x8b, 0x46, 0x59, 0xae,
	0x66, 0x6f, 0x09, 0x7b, 0xfa, 0xd4, 0x77, 0x99, 0x87, 0x8d, 0x35, 0x5d, 0x3b, 0x58, 0xb7, 0x21,
	0x0d, 0x1d, 0x33, 0x0f, 0xc9, 0x2e, 0x00, 0x8f, 0x07, 0xfd, 0x0c, 0xbc, 0x2e, 0xc1, 0x35, 0x1e,
	0x0f, 0x8e, 0x53, 0xfc, 0x4d, 0xb8, 0x3c, 0x59, 0x4e, 0x39, 0x2a, 0x92, 0x63, 0x23, 0xcf, 0x49,
	0x68, 0x8c, 0xfb, 0x50, 0xeb, 0xe5, 0xa0, 0x59, 0x4e, 0x6d, 0x9e, 0x93, 0xc0, 0x9a, 0x24, 0x2a,
	0x49, 0x22, 0xf9, 0x6c, 0x74, 0xa1, 0x92, 0xad, 0x4e, 0x76, 0xa2, 0xcd, 0xec, 0x44, 0xa1, 0xca,
	0x53, 0xa8, 0x33, 0x20, 0x47, 0x9e, 0xa7, 0x8e, 0xd2, 0xc6, 0xe7, 0x31, 0x72, 0x41, 0xee, 0x41,
	0x55, 0x9d, 0x8d, 0xd4, 0xa8, 0x77, 0x9a, 0xe6, 0x7c, 0xb3, 0xcd, 0x1c, 0x94, 0xe7, 0x1a, 0xf7,
	0xe0, 0xed, 0x19, 0x36, 0x1e, 0xb2, 0x80, 0xe3, 0xa2, 0x06, 0xd5, 0xa6, 0x1b, 0x64, 0x7c, 0x04,
	0xdb, 0x36, 0x8e, 0xd9, 0x0b, 0x9c, 0x2f, 0x64, 0x0e, 0x59, 0x2a, 0x20, 0x3f, 0x04, 0xf2, 0x39,
	0x8a, 0x15, 0xb0, 0xa2, 0x60, 0x0f, 0xb6, 0xcf, 0x28, 0x57, 0x38, 0x8a, 0x5c, 0x21, 0x77, 0x01,
	0x42, 0xc7, 0xc7, 0xbe, 0x60, 0xcf, 0x30, 0x90, 0xc0, 0x75, 0xbb, 0x96, 0x44, 0xbe, 0x4a, 0x02,
	0x64, 0x07, 0xe4, 0x4b, 0x9f, 0xd3, 0x57, 0xea, 0xf4, 0xab, 0x49, 0xa0, 0x47, 0x5f, 0xa1, 0xf1,
	0x0c, 0xde, 0xe9, 0xa1, 0x13, 0xb9, 0xc3, 0x22, 0xed, 0x15, 0x58, 0x7f, 0x1e, 0x63, 0xa4, 0x3a,
	0x92, 0xbe, 0xcc, 0x89, 0x95, 0xde, 0x28, 0x56, 0x9e, 0x13, 0x0b, 0x01, 0x26, 0x32, 0xe4, 0x10,
	0xd4, 0xee, 0x28, 0xf2, 0x86, 0xa6, 0x97, 0x57, 0xb4, 0x6c, 0x2a, 0x3b, 0x31, 0x68, 0x80, 0xe7,
	0xa2, 0x5f, 0x28, 0x65, 0x23, 0x09, 0x3f, 0x56, 0xe5, 0x18, 0x0f, 0xa0, 0x2a, 0x0d, 0x96, 0x60,
	0xba, 0x50, 0x75, 0xb3, 0xe7, 0x4c, 0xad, 0x51, 0x54, 0x4b, 0xed, 0x68, 0xe7, 0x99, 0xc6, 0x17,
	0x50, 0x57, 0x16, 0x4f, 0x48, 0xee, 0xc3, 0xa5, 0xdc, 0xe4, 0x13, 0xa2, 0x9d, 0x22, 0x51, 0x3e,
	0x17, 0x76, 0x9d, 0x4f, 0xf0, 0x9d, 0xdf, 0xdf, 0x82, 0xba, 0xda, 0xd1, 0xd1, 0xe3, 0x53, 0xf2,
	0x5a, 0x83, 0xfa, 0x94, 0xfd, 0xc8, 0x8d, 0x22, 0x53, 0xd1, 0xeb, 0xcd, 0xbd, 0x15, 0x59, 0xa9,
	0x87, 0x8d, 0x9b, 0xaf, 0xff, 0xf9, 0xf7, 0xd7, 0x92, 0x6e, 0xec, 0x64, 0xf7, 0x97, 0x84, 0x58,
	0x93, 0x63, 0xb4, 0x1c, 0xcf, 0x3b, 0xd4, 0x5a, 0xe4, 0x47, 0x0d, 0x36, 0x67, 0xbd, 0x4c, 0xf6,
	0x8b, 0x0a, 0x0b, 0xdd, 0xde, 0xbc, 0x6a, 0xa6, 0x57, 0xa4, 0xa9, 0xee, 0x4f, 0xf3, 0x24, 0xb9,
	0x3f, 0x8d, 0xb6, 0xd4, 0xde, 0x6f, 0xed, 0x2d, 0xd3, 0xfe, 0x76, 0xca, 0xed, 0xdf, 0x93, 0x1f,
	0xa0, 0x3e, 0x35, 0x13, 0x8b, 0x8e, 0xa1, 0x38, 0x32, 0xcd, 0x37, 0xb8, 0x45, 0xe9, 0x93, 0xff,
	0xa9, 0xff, 0x93, 0x06, 0x9b, 0xb3, 0xd3, 0xb5, 0xe8, 0x08, 0x16, 0xce, 0x5f, 0xf3, 0xda, 0xd2,
	0x32, 0x12, 0x03, 0xbd, 0x2f, 0x0b, 0xd9, 0x23, 0xd7, 0x97, 0x36, 0xc1, 0x4d, 0xbe, 0x12, 0xd6,
	0x88, 0x72, 0x41, 0x7e, 0xd6, 0x60, 0x6b, 0x7e, 0x1e, 0xc9, 0xad, 0x05, 0xee, 0x5a, 0x3c, 0xb3,
	0x2b, 0x4a, 0x59, 0x79, 0x26, 0x59, 0x29, 0x5c, 0xb2, 0x13, 0x0e, 0x97, 0x92, 0x0d, 0xe7, 0xde,
	0x5f, 0xd2, 0xea, 0x45, 0x6d, 0x50, 0x18, 0xc3, 0x92, 0x92, 0xb7, 0xc8, 0xfe, 0x0a, 0x49, 0x35,
	0x50, 0xe4, 0x3b, 0xb8, 0x9c, 0x88, 0x4e, 0xcf, 0xdc, 0x32, 0xdd, 0xdd, 0xe5, 0x53, 0x97, 0x48,
	0x77, 0xa4, 0xf4, 0x6d, 0xd2, 0x5a, 0xb5, 0xdb, 0x78, 0xa0, 0xd4, 0x1f, 0xfe, 0x59, 0xfa, 0xe5,
	0xe8, 0x8f, 0x12, 0xf9, 0x4b, 0x83, 0x2d, 0xe5, 0x24, 0xbd, 0x87, 0xd1, 0x0b, 0xea, 0xa2, 0xf1,
	0x0d, 0xdc, 0x98, 0x9c, 0xa5, 0xce, 0xd3, 0xa8, 0xde, 0xd6, 0x33, 0x66, 0x3d, 0x8c, 0xd8, 0x53,
	0x74, 0x05, 0x79, 0x6f, 0x28, 0x44, 0xc8, 0x0f, 0x2d, 0xcb, 0xa7, 0x62, 0x18, 0x0f, 0x4c, 0x97,
	0x8d, 0x2d, 0x9f, 0x7a, 0x17, 0x2c, 0x50, 0x45, 0x34, 0xb7, 0x7d, 0xea, 0x21, 0x0b, 0x86, 0x8e,
	0x8b, 0xd1, 0x03, 0x7f, 0xec, 0xd0, 0x51, 0x92, 0xd5, 0xfa, 0x12, 0xae, 0x3c, 0xec, 0x7d, 0xaa,
	0xdf, 0x6d, 0x1f, 0x8f, 0x9c, 0x98, 0xa3, 0x7e, 0x46, 0x5d, 0x4c, 0xbe, 0x45, 0x1f, 0xaf, 0x64,
	0xb4, 0x06, 0x23, 0x36, 0xb0, 0xc6, 0x0e, 0x17, 0x18, 0x59, 0x67, 0xa7, 0xc7, 0x27, 0x8f, 0x7a,
	0x27, 0xa6, 0x38, 0x17, 0x9d, 0xf2, 0x07, 0xe6, 0x9d, 0x56, 0x59, 0x2b, 0xad, 0x75, 0xb6, 0x9c,
	0x30, 0x1c, 0x51, 0x57, 0xfe, 0x25, 0xb1, 0x9e, 0x72, 0x16, 0x1c, 0x16, 0x22, 0xf6, 0x27, 0x50,
	0xee, 0xde, 0xe9, 0x92, 0x2e, 0xb4, 0x6c, 0x14, 0x71, 0x14, 0xa0, 0xa7, 0xbf, 0x1c, 0x62, 0xa0,
	0x8b, 0x21, 0xea, 0x11, 0x72, 0x16, 0x47, 0x2e, 0xea, 0x1e, 0x43, 0xae, 0x07, 0x4c, 0xe8, 0x78,
	0x4e, 0xb9, 0x30, 0x49, 0x05, 0xd6, 0x7e, 0x2b, 0x69, 0x95, 0xaf, 0xf3, 0x4f, 0xea, 0xa0, 0x22,
	0x1b, 0x75, 0xf7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xd0, 0x4e, 0x31, 0x7d, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FacilityAPIClient is the client API for FacilityAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FacilityAPIClient interface {
	// Adds a facility to a list of facilities in the database
	AddFacility(ctx context.Context, in *AddFacilityRequest, opts ...grpc.CallOption) (*AddFacilityResponse, error)
	// Removes a facility in the database
	RemoveFacility(ctx context.Context, in *RemoveFacilityRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Retrieves a facility resource from the database
	GetFacility(ctx context.Context, in *GetFacilityRequest, opts ...grpc.CallOption) (*Facility, error)
	// Retrieves a list of facilities resource from the database
	ListFacilities(ctx context.Context, in *ListFacilitiesRequest, opts ...grpc.CallOption) (*Facilities, error)
	// Searches for facility and returns collection of facilities
	SearchFacilities(ctx context.Context, in *SearchFacilitiesRequest, opts ...grpc.CallOption) (*Facilities, error)
	// Retrieves a collection of counties
	ListCounties(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Counties, error)
	// Retrieves a collection of sub counties
	ListSubCounties(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SubCounties, error)
}

type facilityAPIClient struct {
	cc *grpc.ClientConn
}

func NewFacilityAPIClient(cc *grpc.ClientConn) FacilityAPIClient {
	return &facilityAPIClient{cc}
}

func (c *facilityAPIClient) AddFacility(ctx context.Context, in *AddFacilityRequest, opts ...grpc.CallOption) (*AddFacilityResponse, error) {
	out := new(AddFacilityResponse)
	err := c.cc.Invoke(ctx, "/antibug.facility.FacilityAPI/AddFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityAPIClient) RemoveFacility(ctx context.Context, in *RemoveFacilityRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/antibug.facility.FacilityAPI/RemoveFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityAPIClient) GetFacility(ctx context.Context, in *GetFacilityRequest, opts ...grpc.CallOption) (*Facility, error) {
	out := new(Facility)
	err := c.cc.Invoke(ctx, "/antibug.facility.FacilityAPI/GetFacility", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityAPIClient) ListFacilities(ctx context.Context, in *ListFacilitiesRequest, opts ...grpc.CallOption) (*Facilities, error) {
	out := new(Facilities)
	err := c.cc.Invoke(ctx, "/antibug.facility.FacilityAPI/ListFacilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityAPIClient) SearchFacilities(ctx context.Context, in *SearchFacilitiesRequest, opts ...grpc.CallOption) (*Facilities, error) {
	out := new(Facilities)
	err := c.cc.Invoke(ctx, "/antibug.facility.FacilityAPI/SearchFacilities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityAPIClient) ListCounties(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Counties, error) {
	out := new(Counties)
	err := c.cc.Invoke(ctx, "/antibug.facility.FacilityAPI/ListCounties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *facilityAPIClient) ListSubCounties(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*SubCounties, error) {
	out := new(SubCounties)
	err := c.cc.Invoke(ctx, "/antibug.facility.FacilityAPI/ListSubCounties", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FacilityAPIServer is the server API for FacilityAPI service.
type FacilityAPIServer interface {
	// Adds a facility to a list of facilities in the database
	AddFacility(context.Context, *AddFacilityRequest) (*AddFacilityResponse, error)
	// Removes a facility in the database
	RemoveFacility(context.Context, *RemoveFacilityRequest) (*empty.Empty, error)
	// Retrieves a facility resource from the database
	GetFacility(context.Context, *GetFacilityRequest) (*Facility, error)
	// Retrieves a list of facilities resource from the database
	ListFacilities(context.Context, *ListFacilitiesRequest) (*Facilities, error)
	// Searches for facility and returns collection of facilities
	SearchFacilities(context.Context, *SearchFacilitiesRequest) (*Facilities, error)
	// Retrieves a collection of counties
	ListCounties(context.Context, *empty.Empty) (*Counties, error)
	// Retrieves a collection of sub counties
	ListSubCounties(context.Context, *empty.Empty) (*SubCounties, error)
}

func RegisterFacilityAPIServer(s *grpc.Server, srv FacilityAPIServer) {
	s.RegisterService(&_FacilityAPI_serviceDesc, srv)
}

func _FacilityAPI_AddFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityAPIServer).AddFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.facility.FacilityAPI/AddFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityAPIServer).AddFacility(ctx, req.(*AddFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityAPI_RemoveFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityAPIServer).RemoveFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.facility.FacilityAPI/RemoveFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityAPIServer).RemoveFacility(ctx, req.(*RemoveFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityAPI_GetFacility_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFacilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityAPIServer).GetFacility(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.facility.FacilityAPI/GetFacility",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityAPIServer).GetFacility(ctx, req.(*GetFacilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityAPI_ListFacilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFacilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityAPIServer).ListFacilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.facility.FacilityAPI/ListFacilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityAPIServer).ListFacilities(ctx, req.(*ListFacilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityAPI_SearchFacilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchFacilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityAPIServer).SearchFacilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.facility.FacilityAPI/SearchFacilities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityAPIServer).SearchFacilities(ctx, req.(*SearchFacilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityAPI_ListCounties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityAPIServer).ListCounties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.facility.FacilityAPI/ListCounties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityAPIServer).ListCounties(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FacilityAPI_ListSubCounties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FacilityAPIServer).ListSubCounties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/antibug.facility.FacilityAPI/ListSubCounties",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FacilityAPIServer).ListSubCounties(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _FacilityAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "antibug.facility.FacilityAPI",
	HandlerType: (*FacilityAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFacility",
			Handler:    _FacilityAPI_AddFacility_Handler,
		},
		{
			MethodName: "RemoveFacility",
			Handler:    _FacilityAPI_RemoveFacility_Handler,
		},
		{
			MethodName: "GetFacility",
			Handler:    _FacilityAPI_GetFacility_Handler,
		},
		{
			MethodName: "ListFacilities",
			Handler:    _FacilityAPI_ListFacilities_Handler,
		},
		{
			MethodName: "SearchFacilities",
			Handler:    _FacilityAPI_SearchFacilities_Handler,
		},
		{
			MethodName: "ListCounties",
			Handler:    _FacilityAPI_ListCounties_Handler,
		},
		{
			MethodName: "ListSubCounties",
			Handler:    _FacilityAPI_ListSubCounties_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "facility.proto",
}
